[project]
name = "games4free-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "httpx>=0.28.1",
    "python-dotenv>=1.0.1",
    "python-telegram-bot[job-queue]>=21.9",
]
